name: movie_ui
description: "Movie Recommendation UI Flutter Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  camera: ^0.10.5+5
  path_provider: ^2.1.2
  http: 1.3.0
  path: ^1.9.1
  http_parser: ^4.1.2
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/movie_background.jpg
